//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOFINAL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://elzapatero.uaca/ws", ConfigurationName="ServiceReference1.ServiciosIncidenteSoap")]
    public interface ServiciosIncidenteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elzapatero.uaca/ws/met_ManoObra", ReplyAction="*")]
        decimal met_ManoObra(int horas, decimal salario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elzapatero.uaca/ws/met_ManoObra", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> met_ManoObraAsync(int horas, decimal salario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elzapatero.uaca/ws/met_CostoTotal", ReplyAction="*")]
        decimal met_CostoTotal(decimal manoObra, decimal repuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elzapatero.uaca/ws/met_CostoTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> met_CostoTotalAsync(decimal manoObra, decimal repuesto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosIncidenteSoapChannel : PROYECTOFINAL.ServiceReference1.ServiciosIncidenteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosIncidenteSoapClient : System.ServiceModel.ClientBase<PROYECTOFINAL.ServiceReference1.ServiciosIncidenteSoap>, PROYECTOFINAL.ServiceReference1.ServiciosIncidenteSoap {
        
        public ServiciosIncidenteSoapClient() {
        }
        
        public ServiciosIncidenteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosIncidenteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosIncidenteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosIncidenteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal met_ManoObra(int horas, decimal salario) {
            return base.Channel.met_ManoObra(horas, salario);
        }
        
        public System.Threading.Tasks.Task<decimal> met_ManoObraAsync(int horas, decimal salario) {
            return base.Channel.met_ManoObraAsync(horas, salario);
        }
        
        public decimal met_CostoTotal(decimal manoObra, decimal repuesto) {
            return base.Channel.met_CostoTotal(manoObra, repuesto);
        }
        
        public System.Threading.Tasks.Task<decimal> met_CostoTotalAsync(decimal manoObra, decimal repuesto) {
            return base.Channel.met_CostoTotalAsync(manoObra, repuesto);
        }
    }
}
