//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Login
{
    /// <summary>
    /// Control txtUsuario.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtUsuario;

    /// <summary>
    /// Control rfvUsuario.
    /// </summary>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsuario;

    /// <summary>
    /// Control txtClave.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtClave;

    /// <summary>
    /// Control rfvClave.
    /// </summary>
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvClave;

    /// <summary>
    /// Control btnLogin.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnLogin;
}
